---
# NSO server information
nso:
  url: http://localhost:8080/jsonrpc
  username: admin
  password: admin

target_device: "A3-ASR9K-R6"

xr_package:
  location: "harddisk:/"
  filename: "asr9k-px-5.3.3-smupack.tar"