---
- name: ASR-9K upgrade MOP
  hosts: localhost
  connection: local

  tasks:

  - import_role:
      name: check-sync

  - import_role:
      name: backup-config

  - import_role:
      name: pre-post-checks

  - import_role:
      name: upgrade

  - import_role:
      name: wait-device-up

  - import_role:
      name: pre-post-checks
    vars:
      post_check: true

  - import_role:
      name: post-upgrade

