---
- name: Check-sync
  hosts: localhost
  connection: local

  tasks:

  - import_role:
      name: check-sync

  - import_role:
      name: backup-config

  - import_role:
      name: pre-post-checks

  - import_role:
      name: pre-post-checks
    vars:
      post_check: true

