---
# tasks file for pre-post-checks
- name: device health check
  nso_action:
    url: "{{ nso.url }}"
    username: "{{ nso.username }}"
    password: "{{ nso.password }}"
    path: "/ncs:services/snap:health-samples/snap:device{'{{ target_device }}'}/run"
  register: device_check_result
  changed_when: false
  failed_when: >
    ("output" not in device_check_result) or
    ("success" not in device_check_result.output)

- name: pre-post assessment diff
  nso_action:
    url: "{{ nso.url }}"
    username: "{{ nso.username }}"
    password: "{{ nso.password }}"
    path: "/ncs:services/snap:health-samples/snap:device{'{{ target_device }}'}/diff"
  register: diff_check_result
  changed_when: false
  failed_when: >
    ("output" not in diff_check_result) or
    ("success" not in diff_check_result.output)
  when:
  - post_check is defined
  - post_check | bool
