---
# tasks file for pre-upgrade
# TODO: Not working with latest NED version
- name: disable fpd auto-upgrade
  nso_config:
    url: "{{ nso.url }}"
    username: "{{ nso.username }}"
    password: "{{ nso.password }}"
    data:
      tailf-ncs:devices:
        device:
        - name: "{{ target_device }}"
          config:
           tailf-ned-cisco-ios-xr:admin:
            fpd:
              auto-upgrade: {}
              __state: absent










