---
# tasks file for check-sync

- name: check-sync
  nso_action:
    url: "{{ nso.url }}"
    username: "{{ nso.username }}"
    password: "{{ nso.password }}"
    path: "/ncs:devices/device{'{{ target_device }}'}/check-sync"
  register: check_sync_result
  changed_when: false
  failed_when: ("output" not in check_sync_result) or (check_sync_result.output|length < 1)

- name: sync-from
  nso_action:
    url: "{{ nso.url }}"
    username: "{{ nso.username }}"
    password: "{{ nso.password }}"
    path: "/ncs:devices/device{'{{ target_device }}'}/sync-from"
  when: (check_sync_result.output|first).value != "in-sync"
  register: sync_from_output






